import { SlashItem } from "./types";

export const SLASH_ITEMS: SlashItem[] = [
	// Headings
	{
		id: "h1",
		name: "Heading 1",
		description: "大标题",
		icon: "heading-1",
		category: "标题",
		keywords: ["h1", "heading1", "标题", "大标题"],
		template: "# ",
	},
	{
		id: "h2",
		name: "Heading 2",
		description: "中标题",
		icon: "heading-2",
		category: "标题",
		keywords: ["h2", "heading2", "标题", "中标题"],
		template: "## ",
	},
	{
		id: "h3",
		name: "Heading 3",
		description: "小标题",
		icon: "heading-3",
		category: "标题",
		keywords: ["h3", "heading3", "标题", "小标题"],
		template: "### ",
	},
	{
		id: "h4",
		name: "Heading 4",
		description: "四级标题",
		icon: "heading-4",
		category: "标题",
		keywords: ["h4", "heading4", "标题"],
		template: "#### ",
	},
	{
		id: "h5",
		name: "Heading 5",
		description: "五级标题",
		icon: "heading-5",
		category: "标题",
		keywords: ["h5", "heading5", "标题"],
		template: "##### ",
	},
	{
		id: "h6",
		name: "Heading 6",
		description: "六级标题",
		icon: "heading-6",
		category: "标题",
		keywords: ["h6", "heading6", "标题"],
		template: "###### ",
	},

	// Lists
	{
		id: "ul",
		name: "Bullet List",
		description: "无序列表",
		icon: "list",
		category: "列表",
		keywords: ["ul", "list", "bullet", "无序", "列表"],
		template: "- ",
	},
	{
		id: "ol",
		name: "Numbered List",
		description: "有序列表",
		icon: "list-ordered",
		category: "列表",
		keywords: ["ol", "ordered", "number", "有序", "列表", "编号"],
		template: "1. ",
	},
	{
		id: "task",
		name: "Task List",
		description: "任务列表 / 待办事项",
		icon: "check-square",
		category: "列表",
		keywords: ["task", "todo", "checkbox", "任务", "待办"],
		template: "- [ ] ",
	},

	// Blocks
	{
		id: "code",
		name: "Code Block",
		description: "代码块",
		icon: "code",
		category: "块",
		keywords: ["code", "codeblock", "代码", "代码块"],
		template: "```\n\n```",
		cursorOffset: -4,
	},
	{
		id: "quote",
		name: "Quote",
		description: "引用块",
		icon: "quote",
		category: "块",
		keywords: ["quote", "blockquote", "引用"],
		template: "> ",
	},
	{
		id: "callout",
		name: "Callout",
		description: "高亮提示块",
		icon: "message-square",
		category: "块",
		keywords: ["callout", "admonition", "提示", "高亮"],
		template: "> [!NOTE]\n> ",
	},
	{
		id: "table",
		name: "Table",
		description: "表格",
		icon: "table",
		category: "块",
		keywords: ["table", "表格"],
		template: "| Column 1 | Column 2 |\n| -------- | -------- |\n|          |          |",
		cursorOffset: -12,
	},

	// Divider
	{
		id: "hr",
		name: "Horizontal Rule",
		description: "分割线",
		icon: "minus",
		category: "分隔",
		keywords: ["hr", "divider", "line", "分割线", "分隔"],
		template: "---\n",
	},

	// Links
	{
		id: "link",
		name: "Link",
		description: "链接",
		icon: "link",
		category: "链接",
		keywords: ["link", "url", "链接", "网址"],
		template: "[](url)",
		cursorOffset: -6,
	},
	{
		id: "image",
		name: "Image",
		description: "图片",
		icon: "image",
		category: "链接",
		keywords: ["image", "img", "图片"],
		template: "![](url)",
		cursorOffset: -6,
	},

	// Obsidian-specific
	{
		id: "embed",
		name: "Embed File",
		description: "嵌入文件",
		icon: "file-input",
		category: "嵌入",
		keywords: ["embed", "file", "嵌入", "文件"],
		template: "![[]]",
		cursorOffset: -2,
	},
	{
		id: "mermaid",
		name: "Mermaid Diagram",
		description: "Mermaid 流程图",
		icon: "git-branch",
		category: "图表",
		keywords: ["mermaid", "diagram", "流程图", "图表"],
		template: "```mermaid\n\n```",
		cursorOffset: -4,
	},
	{
		id: "math",
		name: "Math Block",
		description: "数学公式块",
		icon: "sigma",
		category: "数学",
		keywords: ["math", "formula", "latex", "数学", "公式"],
		template: "$$\n\n$$",
		cursorOffset: -3,
	},
	{
		id: "footnote",
		name: "Footnote",
		description: "脚注",
		icon: "footprints",
		category: "引用",
		keywords: ["footnote", "fn", "脚注"],
		template: "[^1]: ",
	},
	{
		id: "tag",
		name: "Tag",
		description: "标签",
		icon: "tag",
		category: "标签",
		keywords: ["tag", "标签"],
		template: "#",
	},
];
